# Site settings
title: Alternative Internet
email: hello@redecentralize.org
description: > # this means to ignore newlines until "baseurl:"
  A collection of interesting new networks and tech aiming at decentralisation (in some form).
baseurl: /alternative-internet
url: "http://redecentralize.github.io" # the base hostname & protocol for your site
twitter_username: redecentralize
github_username:  redecentralize

# Build settings
markdown: kramdown

